// <auto-generated />
using System;
using ApiMestre.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMestre.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230626155223_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiMestre.Data.Entities.Alunos", b =>
                {
                    b.Property<Guid>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDALUNO");

                    b.Property<string>("DatadeNascimento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DATANASCIMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Faixa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FAIXA");

                    b.Property<Guid>("IdMestre")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDMESTRE");

                    b.Property<Guid>("IdPresenca")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDPRESECA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOME");

                    b.HasKey("IdAluno");

                    b.HasIndex("IdMestre");

                    b.ToTable("ALUNO", (string)null);
                });

            modelBuilder.Entity("ApiMestre.Data.Entities.Mestre", b =>
                {
                    b.Property<Guid?>("IdMestre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDMESTRE");

                    b.Property<string>("DatadeNascimento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DATANASCIMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("EMIAL");

                    b.Property<string>("Faixa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FAIXA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NOME");

                    b.HasKey("IdMestre");

                    b.ToTable("METRE", (string)null);
                });

            modelBuilder.Entity("ApiMestre.Data.Entities.Presenca", b =>
                {
                    b.Property<Guid>("IdPresenca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDPRESNCA");

                    b.Property<string>("Datadehj")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DATA_DE_HOJE");

                    b.Property<Guid>("IdAluno")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDALUNO");

                    b.Property<string>("Presencas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PRESENCAS");

                    b.HasKey("IdPresenca");

                    b.HasIndex("IdAluno");

                    b.ToTable("PRESENCA", (string)null);
                });

            modelBuilder.Entity("ApiMestre.Data.Entities.Alunos", b =>
                {
                    b.HasOne("ApiMestre.Data.Entities.Mestre", "Mestre")
                        .WithMany("Alunos")
                        .HasForeignKey("IdMestre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mestre");
                });

            modelBuilder.Entity("ApiMestre.Data.Entities.Presenca", b =>
                {
                    b.HasOne("ApiMestre.Data.Entities.Alunos", "Alunos")
                        .WithMany("Presenca")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("ApiMestre.Data.Entities.Alunos", b =>
                {
                    b.Navigation("Presenca");
                });

            modelBuilder.Entity("ApiMestre.Data.Entities.Mestre", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
